plugins/nf-validation/src/main/nextflow/validation/SchemaValidator.groovy
plugins/nf-validation/src/test/nextflow/validation/PluginExtensionMethodsTest.groovy
plugins/nf-validation/src/testResources/nextflow_schema.json

Passing a parameter name to --help will print the complete information for that parameter.
Some examples:
An exception is returned if the parameter doesn't exist

Pass a parameter name to --help to print the complete information

---

plugins/nf-validation/src/main/nextflow/validation/SchemaValidator.groovy
plugins/nf-validation/src/test/nextflow/validation/PluginExtensionMethodsTest.groovy

Always print the options of an argument with the help message. 
The output with too many options which are chopped looks like this:

print argument enums in help message

---

plugins/nf-validation/src/main/nextflow/validation/SchemaValidator.groovy

Remove `version` form core Nextflow parameters to check. This is done to allow a `--version` option in pipelines which reports the version of the pipeline.
Slack [discussion](https://nfcore.slack.com/archives/CUC8PPDL2/p1677229836508589).

don't check for version param

---

plugins/nf-validation/src/main/nextflow/validation/FormatValidators/DirectoryPathExistsValidator.groovy
plugins/nf-validation/src/main/nextflow/validation/FormatValidators/FilePathExistsValidator.groovy
plugins/nf-validation/src/main/nextflow/validation/FormatValidators/PathExistsValidator.groovy
plugins/nf-validation/src/main/nextflow/validation/FormatValidators/PathValidator.groovy
plugins/nf-validation/src/main/nextflow/validation/SamplesheetConverter.groovy
plugins/nf-validation/src/main/nextflow/validation/SchemaValidator.groovy
plugins/nf-validation/src/test/nextflow/validation/SamplesheetConverterTest.groovy
plugins/nf-validation/src/testResources/correct.csv
plugins/nf-validation/src/testResources/correct.tsv
plugins/nf-validation/src/testResources/correct.yaml
plugins/nf-validation/src/testResources/errors.csv
plugins/nf-validation/src/testResources/schema_input.json

This PR adds/changes following formats:
- `file-path`: Simply state that this is a file without checking its existence
- `file-path-exists`: Also check for the existence of this file
- `directory-path`: Simply state that this is a directory without checking its existence
- `directory-path-exists`: Also check for the existence of this directory
- `path`: Simply state that this is a file or directory without checking its existence
- `path-exists`: Also check for the existence of this file or directory
Fixes #18

Add more formats for file types

---

plugins/nf-validation/src/main/nextflow/validation/SchemaValidator.groovy

Changes the priority of the immutable meta options, it's now like this:
1. The option of the channel factory `immutable_meta`
2. The parameter specified by the user
3. The default of `true`
This fixes a bug where `validateParameters()` was setting the `validationImmutableMeta` parameter to `true` causing the factory option to break. The reasoning for this change is that if a developer chooses to use the `LinkedHashMap` over the `ImmutableMeta` the user shouldn't change it back as it will almost certainly break everything

change priority to fix the immutable meta bug

---

CHANGELOG.md
plugins/nf-validation/src/main/nextflow/validation/SamplesheetConverter.groovy

Allow quoted fields for csv files in .fromSamplesheet()

---

CHANGELOG.md
docs/parameters/summary_log.md
plugins/nf-validation/src/main/nextflow/validation/SchemaValidator.groovy

assume default 'false'

---

docs/samplesheets/fromSamplesheet.md
plugins/nf-validation/src/main/nextflow/validation/SamplesheetConverter.groovy
plugins/nf-validation/src/main/nextflow/validation/SchemaValidator.groovy
plugins/nf-validation/src/test/nextflow/validation/SamplesheetConverterTest.groovy
plugins/nf-validation/src/testResources/duplicate.csv

Duplicate checking

---

mkdocs.yml

Remove navigation tabs, to find extended documentation easier to find.

Remove navigation tabs

---

docs/samplesheets/examples.md

- Changes samplesheet examples to start simple and build up
- Moves splitting example to middle region
- Tries to harmonise examples to use the same or similar channels. This idea should be taken further.

Add samplesheet examples

---

CHANGELOG.md
plugins/nf-validation/src/main/nextflow/validation/SchemaValidator.groovy

Parameters defined in the schema top level or within `definitions` are considered `expectedParams`.
```json
{
"$schema": "http://json-schema.org/draft-07/schema",
"type": "object",
// Top level params
"properties": {
"test_param_1": { 
"type": "string"
}
},
// Definition groups
"definitions": { 
"my_group_of_params": { 
"title": "A virtual grouping used for docs and pretty-printing",
"type": "object",
"required": ["foo", "bar"], 
"properties": { 
"foo": { 
"type": "string"
},
"bar": {
"type": "string"
}
}
},
// Params within definitions but not inside one of the definitions
"properties": {
"test_param_2": { 
"type": "string"
}
}
},
// Contents of each definition group brought into main schema for validation
"allOf": [
{ "$ref": "#/definitions/my_group_of_params" } ,
{ "$ref": …
```

add parameters from schema top level as expected params

---

CHANGELOG.md
docs/samplesheets/fromSamplesheet.md
plugins/nf-validation/src/main/nextflow/validation/SchemaValidator.groovy
plugins/nf-validation/src/test/nextflow/validation/SamplesheetConverterTest.groovy

1. `schema_filename` option from `fromSamplesheet` has been renamed to `parameters_schema` here to make it more clear to the user that it is used for the parameters schema and not for the samplesheet schema.
2. Added an additional check to `fromSamplesheet` that shows an error if the input parameter hasn't been found in the schema

rename the schema_filename option from fromSamplesheet

---

CHANGELOG.md
plugins/nf-validation/src/main/nextflow/validation/SchemaValidator.groovy

Close #48 and #84 
Use the `params` map to retrieve the value of the specified param instead of `paramsJson` which does not contain parameters evaluating to false.

fix error when a parameter is not present in the schema and evaluates to false

---

CHANGELOG.md
docs/parameters/help_text.md
docs/parameters/summary_log.md
plugins/nf-validation/src/main/nextflow/validation/SchemaValidator.groovy
plugins/nf-validation/src/test/nextflow/validation/PluginExtensionMethodsTest.groovy

This changes monochrome logs to being an option in paramsSummaryLog(), paramsSummaryMap() and paramsHelp().
This makes the structure more flexible for pipeline developers who can now use params.monochrome_logs or handle it with their own tooling.
Fixes #99

Monochrome logs is option in functions rather than global parameter

---

CHANGELOG.md
docs/parameters/help_text.md
docs/parameters/validation.md
plugins/nf-validation/src/main/nextflow/validation/SchemaValidator.groovy
plugins/nf-validation/src/test/nextflow/validation/PluginExtensionMethodsTest.groovy

All optional parameters are not provided though a map:
`validateParameters(parameters_schema: 'my_params.json')`
The same modification was also made for `paramsSummaryMap()`
⚠️ This will break pipelines who were previously providing a path using the `schemaFilename` argument `validateParameters(schemaFilename = 'my_params.json')`

provide schema path through the options map in validateParameters()

---

CHANGELOG.md
plugins/nf-validation/src/main/nextflow/validation/SamplesheetConverter.groovy
plugins/nf-validation/src/test/nextflow/validation/SamplesheetConverterTest.groovy
plugins/nf-validation/src/testResources/correct.csv
plugins/nf-validation/src/testResources/correct.tsv
plugins/nf-validation/src/testResources/correct.yaml

Fixes #112 
=> Also adds the `null` type to be a bit closer to full support of all types.
I'll handle `array` in the hackathon :p

Improve samplesheet typecasting

---

plugins/nf-validation/src/main/nextflow/validation/SchemaValidator.groovy

Fixes #90 
It turns out `replaceAll` to remove `null` values from the json string representation of the samplesheet is the bottleneck here. 
Using `JsonGenerator` with `.excludeNulls` to convert the object to a string and back again to a `JSONArray` solves this. 
Using a single-end samplesheet with 60 rows:
*before*
```
Oct-18 11:57:31.911 [main] DEBUG nextflow.validation.SchemaValidator - Starting validation: 'samplesheet.se.60.csv' with 'assets/schema_input.json'
Oct-18 11:57:31.916 [main] DEBUG nextflow.validation.SchemaValidator - Removing null
Oct-18 12:07:39.610 [main] DEBUG nextflow.validation.SchemaValidator - nulls removed
Oct-18 12:07:39.613 [main] DEBUG nextflow.validation.SchemaValidator - Validation passed: 'samplesheet.se.60.csv' with 'assets/schema_input.json'
```
*after* …

slow validation caused by string replaceAll to remove nulls

---

CHANGELOG.md
plugins/nf-validation/src/main/nextflow/validation/SchemaValidator.groovy
plugins/nf-validation/src/resources/META-INF/MANIFEST.MF
plugins/nf-validation/src/test/nextflow/validation/PluginExtensionMethodsTest.groovy
plugins/nf-validation/src/testResources/nextflow_schema.json
plugins/nf-validation/src/testResources/wrong.yaml

This PR contains a fix for the YAML validation skip reported in #121 and the preparation for a patch release

Fix YAML validation + prepare for patch release

---

CHANGELOG.md
plugins/nf-validation/src/main/nextflow/validation/FormatValidators/FilePathPatternValidator.groovy
plugins/nf-validation/src/resources/META-INF/MANIFEST.MF
plugins/nf-validation/src/test/nextflow/validation/PluginExtensionMethodsTest.groovy
plugins/nf-validation/src/testResources/nextflow_schema_file_path_pattern.json

Bug reported in the `nf-core/mag` pipeline (https://github.com/nf-core/mag/pull/541). When giving a single file as input of a parameter with format `file-path-pattern`, the validator would see it as a `Path` type instead of an `ArrayList` type. By simply changing the `Nextflow.file` function to `Nextflow.files`, an `ArrayList` will always be created.

Bug fix for file path patterns

---

parameters_meta_schema.json

See https://github.com/nf-core/tools/issues/2436
Still missing conditional validation - eg. that `maxLength` is only set when `"type": "string"`

Parameters meta-schema - first draft

---

.github/workflows/build-docs.yml

https://github.com/nextflow-io/nf-validation/pull/156 did not work, so trying something else

fetch all comits when building docs

---

plugins/nf-validation/src/main/nextflow/validation/JsonSchemaValidator.groovy

https://github.com/nextflow-io/nf-validation/issues/159

improve error message when detecting the old schema draft
